Add marker based pagination to list users endpoint
box/box-ios-sdk pull request #690
Opened 2019-12-11 20:59 UTC by sujaygarlanka

### Issue Link :link:
- https://jira.inside-box.net/browse/SDK-1212

### Goals :soccer:
- Add marker based pagination to list users endpoint

### Implementation Details :construction:
- Added usemarker and marker parameters to listForEnterprise()

### Testing Details :mag:
- Unit testing

2019-12-11 20:59 UTC, boxcla commented
Verified that @sujaygarlanka has signed the CLA. Thanks for the pull request!

2019-12-12 19:54 UTC, PJSimon requested changes
See proposed change

2019-12-12 19:54 UTC, PJSimon commented on Sources/Modules/UsersModule.swift
> +            "offset": offset,
```suggestion
```

2019-12-13 04:00 UTC, PJSimon approved these changes

2019-12-14 01:52 UTC, merged